newIssueWelcomeComment: >
  Thanks for opening for issue here! Be sure to follow the issue template! Mentors will soon assign you :)
  We get a lot of pull requests on this repo, so please be patient and we will get back to you as soon as we can.ğŸ˜ŠğŸ˜Š


newPRWelcomeComment: >
  Thanks for opening this pull request! Mentors will soon Review your PR :)


firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰

